import cv2
import mediapipe as mp
import time

BaseOptions = mp.tasks.BaseOptions
PoseLandmarker = mp.tasks.vision.PoseLandmarker
PoseLandmarkerOptions = mp.tasks.vision.PoseLandmarkerOptions
HandLandmarker = mp.tasks.vision.HandLandmarker
HandLandmarkerOptions = mp.tasks.vision.HandLandmarkerOptions
VisionRunningMode = mp.tasks.vision.RunningMode

class PoseDetector:
    def __init__(self, mode=False, max_hands=2, detection_con=0.5, track_con=0.5):
        # Using the downloaded .task files in the 'models' directory
        pose_model_path = 'models/pose_landmarker_lite.task'
        hand_model_path = 'models/hand_landmarker.task'

        pose_options = PoseLandmarkerOptions(
            base_options=BaseOptions(model_asset_path=pose_model_path),
            running_mode=VisionRunningMode.VIDEO,
            output_segmentation_masks=True,
            min_pose_detection_confidence=detection_con,
            min_tracking_confidence=track_con
        )
        self.pose_landmarker = PoseLandmarker.create_from_options(pose_options)

        hand_options = HandLandmarkerOptions(
            base_options=BaseOptions(model_asset_path=hand_model_path),
            running_mode=VisionRunningMode.VIDEO,
            num_hands=max_hands,
            min_hand_detection_confidence=detection_con,
            min_tracking_confidence=track_con
        )
        self.hand_landmarker = HandLandmarker.create_from_options(hand_options)

        # Drawing utilities for legacy rendering if needed (we aren't really drawing in main loop)
        self.mp_pose = mp.solutions.pose if hasattr(mp, 'solutions') and hasattr(mp.solutions, 'pose') else None
        self.mp_hands = mp.solutions.hands if hasattr(mp, 'solutions') and hasattr(mp.solutions, 'hands') else None
        self.mp_draw = mp.solutions.drawing_utils if hasattr(mp, 'solutions') and hasattr(mp.solutions, 'drawing_utils') else None

        self.pose_result = None
        self.hand_result = None
        
        # In Tasks API Video mode, you must provide monotonic increasing timestamps
        self.frame_timestamp_ms = 0

    def find_landmarks(self, img, draw=False):
        """Processes the image and finds both pose and hands landmarks using Tasks API."""
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=img_rgb)
        
        # Ensure timestamp is strictly increasing
        self.frame_timestamp_ms += 33  # roughly 30 FPS representation

        self.pose_result = self.pose_landmarker.detect_for_video(mp_image, self.frame_timestamp_ms)
        self.hand_result = self.hand_landmarker.detect_for_video(mp_image, self.frame_timestamp_ms)

        # Drawing with Tasks API is slightly different manually, but we disabled draw anyway in our main app
        return img

    def get_pose_landmarks(self, img_shape):
        """Returns a list of pose landmarks [id, x, y, z]"""
        lm_list = []
        if self.pose_result and self.pose_result.pose_landmarks:
            h, w, c = img_shape
            # The Tasks API returns a list of landmarks for ONE person (or multiple if configured)
            # pose_landmarks is a list of lists of NormalizedLandmark
            for id, lm in enumerate(self.pose_result.pose_landmarks[0]):
                cx, cy = int(lm.x * w), int(lm.y * h)
                lm_list.append([id, cx, cy, lm.z])
        return lm_list

    def get_hand_landmarks(self, img_shape):
        """Returns a list of hands, where each hand is a list of landmarks [id, x, y, z]"""
        hands_list = []
        if self.hand_result and self.hand_result.hand_landmarks:
            h, w, c = img_shape
            for hand_lms in self.hand_result.hand_landmarks:
                hand_points = []
                for id, lm in enumerate(hand_lms):
                    cx, cy = int(lm.x * w), int(lm.y * h)
                    hand_points.append([id, cx, cy, lm.z])
                hands_list.append(hand_points)
        return hands_list

    def get_segmentation_mask(self):
        """Returns the segmentation mask generated by the pose model as a numpy array."""
        if self.pose_result and self.pose_result.segmentation_masks:
            # segmentation_masks is a list of mp.Image objects (e.g., confidence masks)
            # We take the first one
            mask_image = self.pose_result.segmentation_masks[0]
            # Convert mp.Image to numpy array
            return mask_image.numpy_view()
        return None
